#!/usr/bin/env python

import os

from coverage.cmdline import main as coverage_main
try:
    from coveralls import cli as coveralls_cli
except ImportError as error:
    coveralls_cli = None
try:
    from codecov import main as codecov_main
except ImportError as error:
    codecov_main = None


if (os.environ.get('TESTS', '1') == '1' and
        os.environ.get('TEST_ENABLE', '1') == '1' and
        not os.environ.get('LINT_CHECK') == '1' and
        not os.environ.get('SKIP_COVERAGE', '0') == '1'):
    coverage_main(["report", "--show-missing"])
    try:
        if coveralls_cli:
            coveralls_cli.main(argv=None)
        else:
            print("No coveralls module, skipping.")
    except:
        pass
    try:
        if codecov_main:
            codecov_main(argv=None)
        else:
            print("No coveralls module, skipping.")
    except:
        pass
